<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CombinedMapping</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FlowMapper\FlowMapper.csproj" />
    <ProjectReference Include="..\..\src\FlowMapper.DependencyInjection\FlowMapper.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\FlowMapper.Providers.SqlServer\FlowMapper.Providers.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\FlowMapper.Providers.PostgreSql\FlowMapper.Providers.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\FlowMapper.Providers.MySql\FlowMapper.Providers.MySql.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>
</Project>
