<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PackageId>FlowMapper.Cli</PackageId>
    <Description>Ferramenta de linha de comando do FlowMapper.</Description>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
      <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>

