<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>true</IsPackable>

    <!-- Informações de pacote -->
    <PackageId>FlowMapper</PackageId>
    <Description>Compile-time object mapping framework powered by Roslyn source generators. Zero runtime reflection.</Description>
    <PackageReadmeFile>README.nuget.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowMapper.Abstractions\FlowMapper.Abstractions.csproj" />
    <ProjectReference Include="..\FlowMapper.Core\FlowMapper.Core.csproj" />
    <ProjectReference Include="..\FlowMapper.DependencyInjection\FlowMapper.DependencyInjection.csproj" />
    <ProjectReference Include="..\FlowMapper.SourceGenerator\FlowMapper.SourceGenerator.csproj" />
    <ProjectReference Include="..\FlowMapper.Analyzers\FlowMapper.Analyzers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.nuget.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
