using FlowMapper.Abstractions;
using FlowMapper.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;

var services = new ServiceCollection();
services.AddFlowMapper();

// Register manual mapper (normally generated by FlowMapper SourceGenerator)
services.AddTransient<IMapper<User, UserDto>, UserToUserDtoMapper>();

var provider = services.BuildServiceProvider();

var mapper = provider.GetRequiredService<IFlowMapper>();
var dto = mapper.Map<User, UserDto>(new User { Id = 1, Name = "Alice" });

Console.WriteLine($"{dto.Id}: {dto.Name}");

// Manual mapper — normally generated at compile time via ProfileDefinition.CreateMap<User, UserDto>()
public class UserToUserDtoMapper : IMapper<User, UserDto>
{
    public UserDto Map(User source) => new()
    {
        Id = source.Id,
        Name = source.Name
    };
}

public class User
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
}

public class UserDto
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
}
