using System.Diagnostics;
using System.Text;

namespace FlowMapper.Compiler.Pipeline;

public sealed class SourceGenerationStage : ICompilerStage
{
    public string Name => "Source Generation";

    public CompilerStageResult Execute(CompilerContext context)
    {
        var sw = Stopwatch.StartNew();
        var diagnostics = new List<CompilerDiagnostic>();

        try
        {
            var generated = new List<string>();

            foreach (var artifact in context.Artifacts)
            {
                var source = GenerateDelegateSource(artifact);
                if (source != null)
                    generated.Add(source);
            }

            sw.Stop();
            diagnostics.Add(new CompilerDiagnostic(
                Name, $"Generated {generated.Count} source delegates in {sw.Elapsed.TotalMilliseconds:F1}ms",
                CompilerDiagnosticSeverity.Info));
            return new CompilerStageResult(true, diagnostics.AsReadOnly(), sw.Elapsed);
        }
        catch (Exception ex)
        {
            sw.Stop();
            diagnostics.Add(new CompilerDiagnostic(
                Name, $"Source generation failed: {ex.Message}",
                CompilerDiagnosticSeverity.Error, ex.StackTrace));
            return new CompilerStageResult(false, diagnostics.AsReadOnly(), sw.Elapsed);
        }
    }

    private static string? GenerateDelegateSource(Execution.ExecutionArtifact artifact)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Artifact: {artifact.Name}");
        sb.AppendLine($"// Source: {artifact.SourceType?.Name}");
        sb.AppendLine($"// Destination: {artifact.DestinationType?.Name}");
        sb.AppendLine();
        return sb.ToString();
    }
}
