using FlowMapper.Abstractions;

Console.WriteLine("=== Flatten Mapping ===");
Console.WriteLine("Maps nested source paths to flat destination properties:");
Console.WriteLine("  Employee.Address.Street -> EmployeeDto.AddressStreet");
Console.WriteLine("  Employee.Address.City   -> EmployeeDto.AddressCity");
Console.WriteLine();

var mapper = new EmployeeToEmployeeDtoMapper();
var employee = new Employee
{
    Name = "Bob",
    Address = new Address
    {
        Street = "123 Main St",
        City = "Springfield",
        ZipCode = "12345"
    }
};
var dto = mapper.Map(employee);

Console.WriteLine($"EmployeeDto: Name={dto.Name}");
Console.WriteLine($"  AddressStreet={dto.AddressStreet}");
Console.WriteLine($"  AddressCity={dto.AddressCity}");
Console.WriteLine($"  AddressZipCode={dto.AddressZipCode}");

// --- Manual flat mapper (normally generated by FlowMapper SourceGenerator) ---
// With ProfileDefinition.CreateMap<Employee, EmployeeDto>() and EnableFlatten = true,
// the generator finds leaf paths via DFS and produces code like:
//   dto.AddressStreet = source.Address.Street;

public class EmployeeToEmployeeDtoMapper : IMapper<Employee, EmployeeDto>
{
    public EmployeeDto Map(Employee source) => new()
    {
        Name = source.Name,
        AddressStreet = source.Address.Street,
        AddressCity = source.Address.City,
        AddressZipCode = source.Address.ZipCode
    };
}

public class Address
{
    public string Street { get; set; } = string.Empty;
    public string City { get; set; } = string.Empty;
    public string ZipCode { get; set; } = string.Empty;
}

public class Employee
{
    public string Name { get; set; } = string.Empty;
    public Address Address { get; set; } = new();
}

public class EmployeeDto
{
    public string Name { get; set; } = string.Empty;
    public string AddressStreet { get; set; } = string.Empty;
    public string AddressCity { get; set; } = string.Empty;
    public string AddressZipCode { get; set; } = string.Empty;
}
