<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FlowMapper.Providers.Oracle</RootNamespace>
      <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FlowMapper.Providers.Abstractions\FlowMapper.Providers.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.100" />
  </ItemGroup>
</Project>

