<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FlowMapper.Runtime</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FlowMapper.Execution\FlowMapper.Execution.csproj" />
    <ProjectReference Include="..\FlowMapper.Materializer\FlowMapper.Materializer.csproj" />
    <ProjectReference Include="..\FlowMapper.Providers.Abstractions\FlowMapper.Providers.Abstractions.csproj" />
  </ItemGroup>
</Project>
