<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FlowMapper.DependencyInjection</RootNamespace>
      <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FlowMapper.Abstractions\FlowMapper.Abstractions.csproj" />
    <ProjectReference Include="..\FlowMapper.Core\FlowMapper.Core.csproj" />
    <ProjectReference Include="..\FlowMapper.Runtime\FlowMapper.Runtime.csproj" />
    <ProjectReference Include="..\FlowMapper.Compiler\FlowMapper.Compiler.csproj" />
    <ProjectReference Include="..\FlowMapper.Materializer\FlowMapper.Materializer.csproj" />
    <ProjectReference Include="..\FlowMapper.Diagnostics\FlowMapper.Diagnostics.csproj" />
    <ProjectReference Include="..\FlowMapper.Deserialization\FlowMapper.Deserialization.csproj" />
    <ProjectReference Include="..\FlowMapper.Providers.Abstractions\FlowMapper.Providers.Abstractions.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
  </ItemGroup>
</Project>

