using System.Text;

namespace FlowMapper.SourceGenerator.Pipeline.Generator;

public class UsingWriter : ICodeWriter
{
    public void Write(CodeWriterContext context, StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable CS0105, CS8618, CS0649");
        sb.AppendLine("using FlowMapper.Abstractions;");
        sb.AppendLine("using FlowMapper.Core;");
        sb.AppendLine();
    }
}